Update plugin.json
Goldorion/MCreatorFabricGenerator pull request #181
Opened 2022-03-07 23:38 UTC by Brandonbr1

2022-03-07 23:41 UTC, Goldorion requested changes

2022-03-07 23:41 UTC, Goldorion commented on src/plugin.json
> +    "description": "An Mcreator Fabric generator plugin",
This is not needed.

2022-03-07 23:41 UTC, Goldorion commented on src/plugin.json
> +    "credits": "Thank you to all contributors and Forge 1.17.1 generator for alot of  the code",
```suggestion
    "credits": "Thank you to all contributors and built-in MCreator generators.",
```

2022-03-08 00:03 UTC, Brandonbr1 commented
@Goldorion  Changes done

2022-03-08 00:04 UTC, merged