Added Feature Request Issue Template
Goldorion/MCreatorFabricGenerator pull request #389
Opened 2023-03-04 06:49 UTC by PSGitHubUser1

This PR will add Issue Template for Feature Request which I made and I am using it in my repos. But because you Merged my prev. PR, this is a gift for you. [Holi Special Gift] 

_I know that you not even heard of 'Holi' word. Its an Indian Festival which is on 8th March._

2023-03-08 11:03 UTC, PSGitHubUser1 commented
Updated to new version of 2023.1 [b10219]

2023-03-11 15:57 UTC, Goldorion requested changes

2023-03-11 15:57 UTC, Goldorion commented on src/plugin.json
> +  "maxversion": 202300110610,
why? this is a total regression

2023-03-11 15:58 UTC, Goldorion requested changes
There is always one rule with GitHub. 1 PR = 1 feature, not 3.

2023-03-11 15:58 UTC, Goldorion commented on update.json
> +    "latest": "1.8.7"
not sure if you check the master branch, but you don't.

2023-03-11 15:58 UTC, closed without merging

2023-03-11 16:08 UTC, PSGitHubUser1 commented
> There is always one rule with GitHub. 1 PR = 1 feature, not 3.

Uhh. Ok, I did not knew that. Thanks.